# Generated by Django 3.1 on 2020-08-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
