# Generated by Django 3.1 on 2020-08-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_task_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='weight',
            new_name='height',
        ),
    ]
