# Generated by Django 3.1 on 2020-08-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200828_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='height',
        ),
    ]
