# Generated by Django 3.1 on 2020-08-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_task_height'),
        ('website', '0002_task_important'),
    ]

    operations = [
    ]
